name: Python application
 
on:

  push:

    branches: [ "main" ]

  pull_request:

    branches: [ "main" ]
 
permissions:

  contents: read
 
jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:

    - uses: actions/checkout@v4

    - name: Set up Python 3.10

      uses: actions/setup-python@v3

      with:

        python-version: "3.10"

    - name: Install dependencies

      run: |

        python -m pip install --upgrade pip

        pip install flake8 pytest

        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8

      run: |

        # stop the build if there are Python syntax errors or undefined names

        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide

        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Teste

      run: coverage run app_test.py
 
    - name: relatorio_teste

      run: coverage report -m
 
    - name: Render Deploy Actions

      uses: johnbeynon/render-deploy-action@v0.0.8

      with: 

        service-id: srv-crqbhm68ii6s73cs9ocg

        api-key: rnd_RH37dvtHRwgMsvw2D6EWPScio5yw
 
    - name: Deploy no EC2 - AWS

      run: |

            echo "Conectando no EC2"

            echo "${{secrets.AWS_KEY}}" > private_key && chmod 600 private_key 

            ssh -o StrictHostKeyChecking=no -i private_key ubuntu@ec2-54-172-214-79.compute-1.amazonaws.com "

                cd parte_dados/subindinho/;git pull;./iniciarApp.sh"
 

'''
