name: Python application
 
on:

  push:

    branches: [ "main" ]

  pull_request:

    branches: [ "main" ]
 
permissions:

  contents: read
 
jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:

    - uses: actions/checkout@v4

    - name: Set up Python 3.10

      uses: actions/setup-python@v3

      with:

        python-version: "3.10"

 
    - name: Deploy no EC2 - AWS

      run: |

            echo "Conectando no EC2"

            echo "${{secrets.AWS_KEY}}" > private_key && chmod 600 private_key 

            ssh -o StrictHostKeyChecking=no -i private_key ubuntu@ec2-54-162-95-166.compute-1.amazonaws.com"

                cd parte_dados/subindinho/; && git pull; && ./iniciarApp.sh"
